//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGS_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEF_PRODUCT()
        {
            this.ITEM_LIST_LINE_ITEMS = new HashSet<ITEM_LIST_LINE_ITEMS>();
            this.ORDER_LINE_ITEMS = new HashSet<ORDER_LINE_ITEMS>();
        }
    
        public decimal PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public decimal CATEGORY_ID { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_USER { get; set; }
    
        public virtual DEF_CATEGORY DEF_CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_LIST_LINE_ITEMS> ITEM_LIST_LINE_ITEMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_LINE_ITEMS> ORDER_LINE_ITEMS { get; set; }
    }
}
