//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGS_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_CUSTOMERS
    {
        public string CUSTOMER_ID { get; set; }
        public Nullable<decimal> CONTACT_NO_1 { get; set; }
        public Nullable<decimal> CONTACT_NO_2 { get; set; }
        public string ADDRESS_NO { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_LANE { get; set; }
        public Nullable<decimal> PROVINCE_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
    }
}
