//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGS_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_LIST_LINE_ITEMS
    {
        public string ITEM_LIST_ID { get; set; }
        public decimal PRODUCT_ID { get; set; }
        public string OFFERS_ID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATDE_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_USER { get; set; }
    
        public virtual DEF_OFFERS DEF_OFFERS { get; set; }
        public virtual DEF_PRODUCT DEF_PRODUCT { get; set; }
        public virtual ITEM_LIST ITEM_LIST { get; set; }
    }
}
