//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGS_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_LIST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEM_LIST()
        {
            this.ITEM_LIST_LINE_ITEMS = new HashSet<ITEM_LIST_LINE_ITEMS>();
        }
    
        public string ITEM_LIST_ID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string OFFERS_ID { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_USER { get; set; }
        public string SUPER_MARKET_ID { get; set; }
    
        public virtual DEF_OFFERS DEF_OFFERS { get; set; }
        public virtual DEF_SUPER_MARKET DEF_SUPER_MARKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEM_LIST_LINE_ITEMS> ITEM_LIST_LINE_ITEMS { get; set; }
    }
}
