//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGS_Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OGSEntities : DbContext
    {
        public OGSEntities()
            : base("name=OGSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEF_CATEGORY> DEF_CATEGORY { get; set; }
        public virtual DbSet<DEF_CUSTOMERS> DEF_CUSTOMERS { get; set; }
        public virtual DbSet<DEF_LOCATION> DEF_LOCATION { get; set; }
        public virtual DbSet<DEF_OFFER_TYPE> DEF_OFFER_TYPE { get; set; }
        public virtual DbSet<DEF_OFFERS> DEF_OFFERS { get; set; }
        public virtual DbSet<DEF_PRODUCT> DEF_PRODUCT { get; set; }
        public virtual DbSet<DEF_PROVINCE> DEF_PROVINCE { get; set; }
        public virtual DbSet<DEF_SUPER_MARKET> DEF_SUPER_MARKET { get; set; }
        public virtual DbSet<ITEM_LIST> ITEM_LIST { get; set; }
        public virtual DbSet<ORDER> ORDERS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ITEM_LIST_LINE_ITEMS> ITEM_LIST_LINE_ITEMS { get; set; }
        public virtual DbSet<ORDER_LINE_ITEMS> ORDER_LINE_ITEMS { get; set; }
    }
}
