//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OGS_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public decimal ORDER_ID { get; set; }
        public string SUPER_MARKET_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_USER { get; set; }
        public Nullable<System.DateTime> MODIFIED_DATE { get; set; }
        public string MODIFIED_USER { get; set; }
    
        public virtual DEF_SUPER_MARKET DEF_SUPER_MARKET { get; set; }
    }
}
